package com.clouck.model;

public enum TimeZone {
    Midway_Island("Midway Island", "(GMT-11:00) Midway Island"),
    Samoa("Samoa", "(GMT-11:00) Samoa"),
    Hawaii("Hawaii", "(GMT-10:00) Hawaii"),
    Alaska("Alaska", "(GMT-09:00) Alaska"),
    Pacific_Time("Pacific Time (US &amp; Canada)", "(GMT-08:00) Pacific Time (US &amp; Canada)"),
    Tijuana("Tijuana", "(GMT-08:00) Tijuana"),
    Arizona("Arizona", "(GMT-07:00) Arizona"),
    Chihuahua("Chihuahua", "(GMT-07:00) Chihuahua"),
    Mazatlan("Mazatlan", "(GMT-07:00) Mazatlan"),
    Mountain_Time("Mountain Time (US &amp; Canada)", "(GMT-07:00) Mountain Time (US &amp; Canada)"),
    Central_America("Central America", "(GMT-06:00) Central America"),
    Central_Time("Central Time (US &amp; Canada)", "(GMT-06:00) Central Time (US &amp; Canada)");
//    A13AA("Guadalajara", "(GMT-06:00) Guadalajara"),
//    A14AA("Mexico City", "(GMT-06:00) Mexico City"),
//    AA15A("Monterrey", "(GMT-06:00) Monterrey"),
//    A12AA("Saskatchewan", "(GMT-06:00) Saskatchewan"),
//    AAA("Bogota", "(GMT-05:00) Bogota"),
//    A12AA("Eastern Time (US &amp; Canada)", "(GMT-05:00) Eastern Time (US &amp; Canada)"),
//    AA43A("Indiana (East)", "(GMT-05:00) Indiana (East)"),
//    AAA("Lima", "(GMT-05:00) Lima"),
//    132AAA("Quito", "(GMT-05:00) Quito"),
//    AAxA("Caracas", "(GMT-04:30) Caracas"),
//    AAsxA("Atlantic Time (Canada)", "(GMT-04:00) Atlantic Time (Canada)"),
//    AA4A("La Paz", "(GMT-04:00) La Paz"),
//    AAsA("Santiago", "(GMT-04:00) Santiago"),
//    AA3A("Newfoundland", "(GMT-03:30) Newfoundland"),
//    AAA("Brasilia", "(GMT-03:00) Brasilia"),
//    AAeA("Buenos Aires", "(GMT-03:00) Buenos Aires"),
//    AAxA("Georgetown", "(GMT-03:00) Georgetown"),
//    AAA("Greenland", "(GMT-03:00) Greenland"),
//    AAA("Mid-Atlantic", "(GMT-02:00) Mid-Atlantic"),
//    AAA("Azores", "(GMT-01:00) Azores"),
//    AAA("Cape Verde Is.", "(GMT-01:00) Cape Verde Is."),
//    AAA("Casablanca", "(GMT+00:00) Casablanca"),
//    AAA("Dublin", "(GMT+00:00) Dublin"),
//    AAxA("Edinburgh", "(GMT+00:00) Edinburgh"),
//    AxAA("Lisbon", "(GMT+00:00) Lisbon"),
//    AAA("London", "(GMT+00:00) London"),
//    AAvA("Monrovia", "(GMT+00:00) Monrovia"),
//    AAxcA("UTC", "(GMT+00:00) UTC"),
//    AAxcbA("Amsterdam", "(GMT+01:00) Amsterdam"),
//    AAssA("Belgrade", "(GMT+01:00) Belgrade"),
//    AAbxcA("Berlin", "(GMT+01:00) Berlin"),
//    AAxA("Bern", "(GMT+01:00) Bern"),
//    AAA("Bratislava", "(GMT+01:00) Bratislava"),
//    AAA("Brussels", "(GMT+01:00) Brussels"),
//    AAA("Budapest", "(GMT+01:00) Budapest"),
//    AAA("Copenhagen", "(GMT+01:00) Copenhagen"),
//    AAA("Ljubljana", "(GMT+01:00) Ljubljana"),
//    AAA("Madrid", "(GMT+01:00) Madrid"),
//    AAA("Paris", "(GMT+01:00) Paris"),
//    AAA("Prague", "(GMT+01:00) Prague"),
//    AAA("Rome", "(GMT+01:00) Rome"),
//    AAA("Sarajevo", "(GMT+01:00) Sarajevo"),
//    AAA("Skopje", "(GMT+01:00) Skopje"),
//    AAA("Stockholm", "(GMT+01:00) Stockholm"),
//    AAA("Vienna", "(GMT+01:00) Vienna"),
//    AAA("Warsaw", "(GMT+01:00) Warsaw"),
//    AAA("West Central Africa", "(GMT+01:00) West Central Africa"),
//    AAA("Zagreb", "(GMT+01:00) Zagreb"),
//    AAA("Athens", "(GMT+02:00) Athens"),
//    AAA("Bucharest", "(GMT+02:00) Bucharest"),
//    AAA("Cairo", "(GMT+02:00) Cairo"),
//    AAA("Harare", "(GMT+02:00) Harare"),
//    AAA("Helsinki", "(GMT+02:00) Helsinki"),
//    AAA("Istanbul", "(GMT+02:00) Istanbul"),
//    AAA("Jerusalem", "(GMT+02:00) Jerusalem"),
//    AAA("Kyev", "(GMT+02:00) Kyev"),
//    AAA("Minsk", "(GMT+02:00) Minsk"),
//    AAA("Pretoria", "(GMT+02:00) Pretoria"),
//    AAA("Riga", "(GMT+02:00) Riga"),
//    AAA("Sofia", "(GMT+02:00) Sofia"),
//    AAA("Tallinn", "(GMT+02:00) Tallinn"),
//    AAA("Vilnius", "(GMT+02:00) Vilnius"),
//    AAA("Baghdad", "(GMT+03:00) Baghdad"),
//    AAA("Kuwait", "(GMT+03:00) Kuwait"),
//    AAA("Moscow", "(GMT+03:00) Moscow"),
//    AAA("Nairobi", "(GMT+03:00) Nairobi"),
//    AAA("Riyadh", "(GMT+03:00) Riyadh"),
//    AAA("St. Petersburg", "(GMT+03:00) St. Petersburg"),
//    AAA("Volgograd", "(GMT+03:00) Volgograd"),
//    AAA("Tehran", "(GMT+03:30) Tehran"),
//    AAA("Abu Dhabi", "(GMT+04:00) Abu Dhabi"),
//    AAA("Baku", "(GMT+04:00) Baku"),
//    AAA("Muscat", "(GMT+04:00) Muscat"),
//    AAA("Tbilisi", "(GMT+04:00) Tbilisi"),
//    AAA("Yerevan", "(GMT+04:00) Yerevan"),
//    AAA("Kabul", "(GMT+04:30) Kabul"),
//    AAA("Ekaterinburg", "(GMT+05:00) Ekaterinburg"),
//    AAA("Islamabad", "(GMT+05:00) Islamabad"),
//    AAA("Karachi", "(GMT+05:00) Karachi"),
//    AAA("Tashkent", "(GMT+05:00) Tashkent"),
//    AAA("Chennai", "(GMT+05:30) Chennai"),
//    AAA("Kolkata", "(GMT+05:30) Kolkata"),
//    AAA("Mumbai", "(GMT+05:30) Mumbai"),
//    AAA("New Delhi", "(GMT+05:30) New Delhi"),
//    AAA("Sri Jayawardenepura", "(GMT+05:30) Sri Jayawardenepura"),
//    AAA("Kathmandu", "(GMT+05:45) Kathmandu"),
//    AAA("Almaty", "(GMT+06:00) Almaty"),
//    AAA("Astana", "(GMT+06:00) Astana"),
//    AAA("Dhaka", "(GMT+06:00) Dhaka"),
//    AAA("Novosibirsk", "(GMT+06:00) Novosibirsk"),
//    AAA("Rangoon", "(GMT+06:30) Rangoon"),
//    AAA("Bangkok", "(GMT+07:00) Bangkok"),
//    AAA("Hanoi", "(GMT+07:00) Hanoi"),
//    AAA("Jakarta", "(GMT+07:00) Jakarta"),
//    AAA("Krasnoyarsk", "(GMT+07:00) Krasnoyarsk"),
//    AAA("Beijing", "(GMT+08:00) Beijing"),
//    AAA("Chongqing", "(GMT+08:00) Chongqing"),
//    AAA("Hong Kong", "(GMT+08:00) Hong Kong"),
//    AAA("Irkutsk", "(GMT+08:00) Irkutsk"),
//    AAA("Kuala Lumpur", "(GMT+08:00) Kuala Lumpur"),
//    AAA("Perth", "(GMT+08:00) Perth"),
//    AAA("Singapore", "(GMT+08:00) Singapore"),
//    AAA("Taipei", "(GMT+08:00) Taipei"),
//    AAA("Ulaan Bataar", "(GMT+08:00) Ulaan Bataar"),
//    AAA("Urumqi", "(GMT+08:00) Urumqi"),
//    AAA("Osaka", "(GMT+09:00) Osaka"),
//    AAA("Sapporo", "(GMT+09:00) Sapporo"),
//    AAA("Seoul", "(GMT+09:00) Seoul"),
//    AAA("Tokyo", "(GMT+09:00) Tokyo"),
//    AAA("Yakutsk", "(GMT+09:00) Yakutsk"),
//    AAA("Adelaide", "(GMT+09:30) Adelaide"),
//    AAA("Darwin", "(GMT+09:30) Darwin"),
//    AAA("Brisbane", "(GMT+10:00) Brisbane"),
//    AAA("Canberra", "(GMT+10:00) Canberra"),
//    AAA("Guam", "(GMT+10:00) Guam"),
//    AAA("Hobart", "(GMT+10:00) Hobart"),
//    AAA("Melbourne", "(GMT+10:00) Melbourne"),
//    AAA("Port Moresby", "(GMT+10:00) Port Moresby"),
//    AAA("Sydney", "(GMT+10:00) Sydney"),
//    AAA("Vladivostok", "(GMT+10:00) Vladivostok"),
//    AAA("Magadan", "(GMT+11:00) Magadan"),
//    AAA("New Caledonia", "(GMT+11:00) New Caledonia"),
//    AAA("Solomon Is.", "(GMT+11:00) Solomon Is."),
//    AAA("Auckland", "(GMT+12:00) Auckland"),
//    AAA("Fiji", "(GMT+12:00) Fiji"),
//    AAA("Kamchatka", "(GMT+12:00) Kamchatka"),
//    AAA("Marshall Is.", "(GMT+12:00) Marshall Is."),
//    AAA("Wellington", "(GMT+12:00) Wellington"),
//    AAA("Nuku'alofa", "(GMT+13:00) Nuku'alofa");
    private String key;
    private String value;
    TimeZone(String key, String value) {
        this.key = key;
        this.value = value;
    }
}


